-*- mode: org; -*-

# SNPDoc user guide document.  Adapted from SNPDoc_User_Guide by R.T. Guy.

# created:  09-Mar-2011
# modified: 10-May-2011

# ToDo:

# [2011-07-01 Fri] Make a table with the description of each field in the output.
# [2011-08-02 Tue] Add documentation for the CpG Island '*' (snp affects CpG
#                  sequence)
# [2012-06-18 Mon] Add documentation for local database interaction


#+LaTeX_CLASS: article

* Title

  SNPDoc User Guide

  Richard T. Guy, David R. McWilliams, Wei Wang and Carl D. Langefeld

* Summary

  SNPDoc mines several on-line databases to record information about single
  nucleotide polymorphisms (SNPs) and genomic positions.  There are three
  options for input: a list of SNPs in 'rs' format, a list of chromosomal
  regions, or a list of chromosomal positions.  Output is to a tab-delimited file
  (for ease of spreadsheet import) or to an html file for browser viewing.
  Information captured by SNPDoc includes:

  + Position
  + Chromosome (and link to NCBI)
  + Gene name, description, and aliases if the SNP is in a gene
  + Nearest upstream and downstream genes if the SNP is not in a gene
  + Risk score if the SNP is in a gene (see below for the risk algorithm)
  + Position of the nearest CpG island
  + Variation type if the SNP is in a variation region
  + SNP merge information
  + Links to the NCBI and UCSC information for the SNP

  In all cases, user data in the file will be merged with SNPDoc output.  This
  is of particular benefit analyzing and ranking the results of GWAS studies.

* Installation

  SNPDoc was constructed to be as self-contained as possible.  The install
  script may complain of missing modules, however.  Platform-specific
  instructions are given below for installing missing modules.

** Linux/Unix/Mac

   Download the archive file and unpack in a working directory.  Change to the
   snpdoc directory and as root enter:

   \vspace*{1cm}
   > perl installScript.pl

   \vspace*{1cm}
   By default the software will be installed in /usr/local/ with a link pointing
   to it in /usr/local/bin/.  Type 'snpdoc.pl --help' to verify operation.

   If you do not have root access, you can run snpdoc by giving the fully
   qualified path to the snpdoc.pl executable.  For example:

   \vspace*{1cm}
   > perl /home/username/path/to/snpdoc.pl <options>

   \vspace*{1cm}
   If you receive errors describing missing modules, install them using CPAN.
   For example if the module 'DBI' is missing, enter as root:

   \vspace*{1cm}
   > cpan install DBI

   \vspace*{1cm}
   You may also be able to use your package manager to install packages.

** Windows

   If you do not have Perl installed on your machine obtain it from
   [[http://www.activestate.com/activeperl/]].  Once it installed, open a command
   window and change to the directory where you downloaded snpdoc and type:

   \vspace*{1cm}
   > perl installScriptMSFT.pl

   \vspace*{1cm}
   The script will create a folder called 'snpdoc' in your Program Files
   directory.  Open the file 'test\_results.txt' in the installation directory
   and check for any tests that failed.  There will be instructions for
   installing perl modules that snpdoc needs.

   You may have to add snpdoc to your command path.  Do the following:

   1) Click Start-> Control Panel
   2) Click "Switch to Classic View"
   3) Double click "System"
   4) Click on the Advanced tab
   5) Click Environment Variables
   6) Double click on the variable Path.  This will bring up a box with contents
      that look similar to:

      \verb+C:\Perl\site\bin;C:\Perl\bin;%SystemRoot%\system32;%SystemRoot%; ...+

   7) Find the end of the text and append \verb+';C:\Program Files\snpdoc\bin'+
      (include the semi-colon but not the quotation marks) and click OK.

   8) Click OK several more times to close the "System" control panel

   You should be able to run snpdoc by typing in a command window:

   \verb+C:\my_project\snpdoc <options>+

* Usage
** General

   Running snpdoc without command line options or with the --help flag
   prints the following usage information.

   \begin{verbatim}
   usage:
   snpdoc [options] -infile FILE, where option is one or more of:

   --help          print this help message

   --infile        input file (required)

   --search        search type; one of "snp", "reg", "pos" (default "snp")

   --outfile       output file name; if not specified it will be created
                   from the input file name.

   --outformat     type of output; one of "text" or "html" (default "text")

   --sep           field delimiter in the input file; currently tab and comma
                   are recognized (supply with quotes as "\t" or ",");
                   default comma

   --db            use a database to save and retrieve results

   --dbname        name of the database

   --user          database username

   --stamp         include a random number for use in temporary files

   --verbose       print more information to the console as snpdoc runs

   --ucsc_version  set the UCSC database version; currently hg18 and hg19
                   are recognized (default 19)

   --restart       a snp designation; if given, processing will start at
                   this snp in the file (snp search only)

   \end{verbatim}

   Flags may also be given as '-h', '-o', etc., if the single letter uniquely
   specifies an option.

   Options may also be put into the configuration file which currently is in the
   /data directory of the snpdoc distribution.  In the future this will become a
   user-providable parameter.  If a user name and password are required for a
   database it must be in the configuration file.
   
** SNP Search

   Running SNPDoc with the '--search snp' option (the default) will search a
   number of databases and aggregate this information with information supplied
   by the user (e.g. statistics from a GWAS study).  The expected file format
   has a header line and data lines following, with the SNP in the first column.
   Only the 'rs#' format is currently recognized for a search.  Empty results
   fields will be printed for non-standard names.  Any further columns are
   retained and appended to the columns output by SNPDoc.

** Positional or Regional Search

   Running SNPDoc with the '--search reg' option performs a 'regional search'.
   The expected file format has a header line and the first column with
   chromosomal regions listed as 'chr2:2300-2500', for example.  The region is
   searched and any SNPs found are output in a format suitable for the 'SNP'
   search described previously.  If user data is supplied for the region, this
   data will be printed for each SNP found in the region.  This may create a
   very large output file if your supplied region is large.

   Running SNPDoc with the '--search pos' option performs a 'positional search'.
   The expected file format has a header line and the position description
   should be in the form 'chr2:1234', for example.  If the position corresponds
   to a named snp, that name will be printed in the first column of output.  If
   the snp is not named, risk and classification are not computed.  User data is
   merged with results in either case.

** Local Database Storage

   SNPDoc can use a local database to store results, which will dramatically
   speed up future searches.  As supplied, SNPDoc reads and writes from a SQLite
   database.  This can be created by SNPDoc by supplying the '--db' flag and
   optionally the '--dbname' flag (with a name).  If no name is supplied a
   database named 'snpdoc.sq3' is created.  SNPDoc will then store complete
   results in the database as it executes web searches (incomplete results are
   not stored to force them to be searched again in the future).  For subsequent
   searches, supply '--db' and '-dbname <name>' and the database will be checked
   before searching the web. The database schema is given in the Appendix.

   If a username and password is added to a database these must be supplied in
   the configuration file in the /data directory of the SNPDoc
   distribution. (This inconvenience will be rectified in future releases).

   SNPDoc can be easily modified to use any database with a perl DBI interface.
   See the module DBWrite.pm in the distribution lib directory or contact the
   current maintainer.

** Summary of the Risk Score Algorithm

   SNPDoc uses a modified version of the FASTSNP algorithm (Yuan et al.,
   2006). The algorithm proceeds as follows.

*** Collect the following information for each SNP

    + SNP function annotations from UCSC

    + Transcription factor binding site information from the TFSEARCH
      [[www.cbrc.jp/research/db/TFSEARCH.html]] database (Akiyama, 2011)

    + Significant exonic splicing enhancer (ESE) motifs found by ESEfinder
      [[rulai.cshl.edu]],(Cartegni, 2003)

    + Significant exonic splicing enhancer motifs found by RESCUE-ESE
      [[genes.mit.edu/burge-lab/rescue-ess]], (Fairbrother, 2002)

    + Significant exonic splicing silencer motifs found by FAS-ESS
      [[genes.mit.edu/fas-ess]], (Wang, 2004)

*** Examine the function for the SNP and score as follows

**** If INTERGENIC then risk = 0

**** If STOP\_GAINED or STOP\_LOST then risk = 5
    
**** If INTRONIC

***** If the TFSEARCH results are equivalent for both alleles, risk = 0, classification = "Intronic with no known function"


***** If the TFSEARCH results are not equivalent, risk = 3, classification = "Intronic enhancer"

**** If SPLICE\_SITE then risk = 3 and classification = "Splice site"

**** If 3PRIME\_UTR then

***** If the TFSEARCH results are equivalent for both alleles, risk = 0, classification = "Downstream with no known function"

***** If the TFSEARCH results are not equivalent, risk = 3, classification = "Promoter/Regulatory region"

**** If 5PRIME\_UTR then proceed as for 3PRIME\_UTR

**** If UPSTREAM then

***** If the TFSEARCH results are equivalent for both alleles, risk = 0, classification = "Upstream with no known function"

***** If the TFSEARCH results are not equivalent, risk = 3, classification = "Promoter/Regulatory region"

**** If DOWNSTREAM then

***** If the TFSEARCH results are equivalent for both alleles, risk = 0, classification = "Downstream with no known function"

***** If the TFSEARCH results are not equivalent, risk = 3, classification = "Promoter/Regulatory region"

**** If SYNONYMOUS\_CODING then

***** If the ESE found by ESEfinder are equivalent for each allele, the ESE found by RESCUE-ESE are equivalent, and the splicing silencers found by FAS-ESE are equivalent then risk = 1 and classification = "Sense/Synonymous"

***** Otherwise risk = 3 and classification = "Sense/Synonymous; Splicing Region"

**** If NON\_SYNONYMOUS\_CODING then

***** Get the number of SNP functions whose biotype is "protein coding."
***** If at least one function is of biotype protein coding then
     
****** If the ESE found by ESEfinder are equivalent for each allele, the ESE found by RESCUE-ESE are equivalent, and the splicing silencers found by FAS-ESE are equivalent then risk = 4 and classification = "Mis-Sense (Leading to Non-Conservative Change)."

****** Otherwise risk = 4, classification = "Mis-Sense (Splicing Regulation, Protein Domain Abolished)

***** If no function of biotype protein coding then

******  If the ESE found by ESEfinder are equivalent for each allele, the ESE found by RESCUE-ESE are equivalent, and the splicing silencers found by FAS-ESE are equivalent then risk = 3, classification = "Mis-Sense (Leading to Conservative Change)"

****** Otherwise risk = 3, classification = "Mis-Sense (Conservative); Splicing Regulation"

 The final risk score is the maximum from the above heuristic and the
 classification is that associated with it

* References

  + Akiyama, Yutaka "TFSEARCH: Searching Transcription Factor Binding Sites",
    Computational Biology Research Center (CBRC), AIST , Japan. (Citation
    retrieved from the website in March 2011).

  + Cartegni L., Wang J., Zhu Z., Zhang M. Q., Krainer A. R.; 2003.  ESEfinder:
    a web resource to identify exonic splicing enhancers.  Nucleic Acid
    Research, 2003, 31(13): 3568-3571.

  + Fairbrother WG, Yeh RF, Sharp PA, Burge CB. Predictive identification of
    exonic splicing enhancers in human genes. Science. 2002 Aug
    9;297(5583):1007-13.

  + Guy, R.T., Wang, W., Marion, M.C, Ramos, P.S., Howard, T., and Langefeld,
    C.D., SNPDoc: Integrating genomic data and statistical results. [Submitted]

  + Hsiang-Yu Yuan, Jen-Jie Chiou, Wen-Hsien Tseng, Chia-Hung Liu, Chuan-Kun
    Liu, Yi-Jung Lin, Hui-Hung Wang, Adam Yao, Yuan-Tsong Chen, and Chun-Nan
    Hsu.  FASTSNP: an always up-to-date and extendable service for SNP function
    analysis and prioritization. Nucleic Acids Res., 1 July 2006; 34: W635 -
    W641.

  + Wang, Z., Rolish, M. E., Yeo, G., Tung, V., Mawson, M. and Burge,
    C. B. (2004). Systematic identification and analysis of exonic splicing
    silencers. Cell 119, 831-845.

* Appendix
** SNPDoc Database Scheme

\begin{verbatim}   

    CREATE TABLE variation (
      type varchar(255),
      name varchar(255),
      chr  varchar(2),
      pos1 int,
      pos2 int,
      ncbi_url varchar(255),
      ucsc_url varchar(255),
      chr_url varchar(255),
      near_gene1 varchar(255),
      gene_url1 varchar(255),
      near_gene2 varchar(255),
      gene_url2 varchar(255),
      gene varchar(255),
      description varchar(255),
      gene_url varchar(255),
      alias varchar(255),
      cons_multiz float,
      cons_phast float,
      risk int,
      cpg varchar(255),
      cnv varchar(255),
      maxclass  varchar(255),
      version int,
      merged_to varchar(255),
      date_inserted varchar(25)
    );
    
\end{verbatim}
